import numpy as np
from sklearn.svm import SVC

from tabembedbench.constants import CLASSIFICATION_TASKS, CLASSIFIER_OPTIMIZATION_METRIC
from tabembedbench.evaluators.abstractevaluator import AbstractHPOEvaluator


class SVMClassifierEvaluator(AbstractHPOEvaluator):
    """
    Defines a support vector machine classifier for hyperparameter optimization and evaluation.

    This class extends the AbstractHPOEvaluator and leverages the SVC (Support Vector Classifier)
    model class. It provides mechanisms for defining the hyperparameter search space, scoring
    metrics, and generating predictions using trained models. It is designed to facilitate
    hyperparameter optimization tasks.

    Attributes:
        model_class (type): The class of the model used for evaluation, specifically `SVC`.
    """

    model_class = SVC

    def __init__(self, **kwargs) -> None:
        super().__init__(
            name="Support Vector Classification",
            task_type=CLASSIFICATION_TASKS,
            **kwargs,
        )

    def get_scoring_metric(self) -> str:
        """
        Returns the scoring metric used for optimization.

        Returns:
            str: The sklearn string for the scoring metric.

        """
        return CLASSIFIER_OPTIMIZATION_METRIC

    def _get_search_space(self) -> dict[str, dict]:
        """
        Defines a private method to retrieve the search space for a machine learning model's
        hyperparameter optimization. The search space is represented as a dictionary with
        hyperparameter names as keys and their respective configurations as values.

        Returns:
            dict[str, dict]: A dictionary defining the search space for hyperparameters. Each
            key represents the name of a hyperparameter and its value is a dictionary containing
            the hyperparameter's type, range, and any specific constraints.
        """
        return {
            "C": {"type": "float", "low": 1e-3, "high": 10, "log": True},
            "kernel": {"type": "constant", "value": "rbf"},
            "gamma": {"type": "float", "low": 1e-3, "high": 10, "log": True},
            "degree": {"type": "int", "low": 2, "high": 5},
        }

    def _get_model_predictions(self, model, embeddings: np.ndarray) -> np.ndarray:
        """Gets prediction probabilities for the provided embeddings using the specified model.

        Args:
            model: The trained model used for generating predictions.
            embeddings (np.ndarray): The input data in the form of embeddings that the
                model will use to compute prediction probabilities.

        Returns:
            np.ndarray: An array of prediction probabilities generated by the model.
        """
        return model.predict_proba(embeddings)
